version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: fiverr-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    container_name: fiverr-api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: fiverr-client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mongo_data: